#targets:
#  $default:
#    builders:
#      source_gen:combining_builder:
#        options:
#          build_extensions:
#            '^lib/common/model/{{}}.dart': 'lib/common/model/generated/{{}}.g.dart'
#      freezed:
#        options:
#          build_extensions:
#            '^lib/common/model/{{}}.dart': 'lib/common/model/generated/{{}}.freezed.dart'