import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  final versionFile = File(p.join('lib', 'version.dart'));
  final gitCommit = _runCommand('git rev-parse --short HEAD');
  final buildTime = DateTime.now().toLocal().toString().split('.')[0];

// This file is generated by generate_version.dart
  final content = '''
const String gitCommit = '$gitCommit';
const String buildTime = '$buildTime';
''';

  versionFile.writeAsStringSync(content);
  print(
      'Generated version.dart with git commit: $gitCommit and build time: $buildTime');
}

String _runCommand(String command) {
  final result =
      Process.runSync(command.split(' ')[0], command.split(' ').sublist(1));
  if (result.exitCode != 0) {
    throw Exception('Failed to run command: $command\n${result.stderr}');
  }
  return result.stdout.toString().trim();
}
